"""Added email_confirmed field to User model

Revision ID: cfdde7a4f1e5
Revises: 53d090224502
Create Date: 2023-08-07 12:01:50.876399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfdde7a4f1e5'
down_revision = '53d090224502'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_confirmed')
    # ### end Alembic commands ###
